insert into public_holidays (date,title) values ('2016-01-01','New Years Day');
 insert into public_holidays (date,title) values ('2016-02-08','Chinese New Year');
 insert into public_holidays (date,title) values ('2016-02-09','Chinese New Year Holiday');
 insert into public_holidays (date,title) values ('2016-03-25','Good Friday');
 insert into public_holidays (date,title) values ('2016-05-01','Labour Day');
 insert into public_holidays (date,title) values ('2016-05-02','Labour Day (observed)');
 insert into public_holidays (date,title) values ('2016-05-21','Wesak Day');
 insert into public_holidays (date,title) values ('2016-05-30','Harvest Festival');
 insert into public_holidays (date,title) values ('2016-05-31','Harvest Festival');
 insert into public_holidays (date,title) values ('2016-06-04','Birthday of SPB Yang di Pertuan Agong');
 insert into public_holidays (date,title) values ('2016-07-06','Hari Raya Aidilfitri');
 insert into public_holidays (date,title) values ('2016-07-07','Hari Raya Aidilfitri Holiday');
 insert into public_holidays (date,title) values ('2016-07-08','Public Holiday');
 insert into public_holidays (date,title) values ('2016-08-31','National Day');
 insert into public_holidays (date,title) values ('2016-09-12','Hari Raya Haji');
 insert into public_holidays (date,title) values ('2016-09-16','Malaysia Day');
 insert into public_holidays (date,title) values ('2016-10-01','Birthday of the Governor of Sabah');
 insert into public_holidays (date,title) values ('2016-10-02','Awal Muharram');
 insert into public_holidays (date,title) values ('2016-10-29','Deepavali');
 insert into public_holidays (date,title) values ('2016-12-12','Maulidur Rasul');
 insert into public_holidays (date,title) values ('2016-12-25','Christmas Day');
 insert into public_holidays (date,title) values ('2016-12-26','Christmas Day (observed)');
 insert into public_holidays (date,title) values ('2017-01-01','New Years Day');
 insert into public_holidays (date,title) values ('2017-01-28','Chinese New Year');
 insert into public_holidays (date,title) values ('2017-01-29','Chinese New Year Holiday');
 insert into public_holidays (date,title) values ('2017-04-14','Good Friday');
 insert into public_holidays (date,title) values ('2017-05-01','Labour Day');
 insert into public_holidays (date,title) values ('2017-05-10','Wesak Day');
 insert into public_holidays (date,title) values ('2017-05-30','Harvest Festival');
 insert into public_holidays (date,title) values ('2017-05-31','Harvest Festival');
 insert into public_holidays (date,title) values ('2017-06-03','Birthday of SPB Yang di Pertuan Agong');
 insert into public_holidays (date,title) values ('2017-06-26','Hari Raya Aidilfitri');
 insert into public_holidays (date,title) values ('2017-06-27','Hari Raya Aidilfitri Holiday');
 insert into public_holidays (date,title) values ('2017-08-31','National Day');
 insert into public_holidays (date,title) values ('2017-09-01','Hari Raya Haji');
 insert into public_holidays (date,title) values ('2017-09-16','Malaysia Day');
 insert into public_holidays (date,title) values ('2017-09-22','Awal Muharram');
 insert into public_holidays (date,title) values ('2017-10-07','Birthday of the Governor of Sabah');
 insert into public_holidays (date,title) values ('2017-10-19','Diwali');
 insert into public_holidays (date,title) values ('2017-12-01','Mawlid');
 insert into public_holidays (date,title) values ('2017-12-25','Christmas Day');
 insert into public_holidays (date,title) values ('2017-12-26','Christmas Holiday');
